-- MySQL Script generated by MySQL Workbench
-- Mon Aug 10 16:25:06 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=1;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=1;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gitdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gitdb` ;

-- -----------------------------------------------------
-- Schema gitdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gitdb` DEFAULT CHARACTER SET utf8 ;
USE `gitdb` ;

-- -----------------------------------------------------
-- Table `gitdb`.`Project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gitdb`.`Project` ;

CREATE TABLE IF NOT EXISTS `gitdb`.`Project` (
  `projectId` INT,
  `projectName` CHAR(50),
  `gitlabToken` VARCHAR(64),
  PRIMARY KEY (`projectId`),
  UNIQUE INDEX `idProject_UNIQUE` (`projectId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gitdb`.`Repository`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gitdb`.`Repository` ;

CREATE TABLE IF NOT EXISTS `gitdb`.`Repository` (
  `url` VARCHAR(256) NOT NULL,
  `id` VARCHAR(32) NOT NULL,
  `service` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`id`, `service`),
  UNIQUE INDEX `URL_UNIQUE` (`url` ASC) VISIBLE,
  INDEX `service_idx` (`service` ASC) VISIBLE)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `gitdb`.`ProjectRepo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gitdb`.`ProjectRepo` ;

CREATE TABLE IF NOT EXISTS `gitdb`.`ProjectRepo` (
  `projectId` INT NOT NULL,
  `idRepo` VARCHAR(32) NOT NULL,
  `serviceRepo` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`projectId`, `idRepo`, `serviceRepo`),
  INDEX `url_idx` (`idRepo` ASC) VISIBLE,
  CONSTRAINT `url`
    FOREIGN KEY (`idRepo`)
    REFERENCES `gitdb`.`Repository` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
CONSTRAINT `repoIdInProject`
    FOREIGN KEY (`serviceRepo`)
    REFERENCES `gitdb`.`Repository` (`service`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `projectIdForRepo`
    FOREIGN KEY (`projectId`)
    REFERENCES `gitdb`.`Project` (`projectId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `gitdb`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gitdb`.`Student` ;

CREATE TABLE IF NOT EXISTS `gitdb`.`Student` (
  `email` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`email`),
  UNIQUE INDEX `emailStudent_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gitdb`.`StudentProject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gitdb`.`StudentProject` ;

CREATE TABLE IF NOT EXISTS `gitdb`.`StudentProject` (
  `emailStudent` VARCHAR(64) NOT NULL,
  `projectId` INT NOT NULL,
  PRIMARY KEY (`emailStudent`, `projectId`),
  INDEX `idProject_idx` (`projectId` ASC) VISIBLE,
  CONSTRAINT `projectId`
    FOREIGN KEY (`projectId`)
    REFERENCES `gitdb`.`Project` (`projectId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idStudent`
    FOREIGN KEY (`emailStudent`)
    REFERENCES `gitdb`.`Student` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gitdb`.`Teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gitdb`.`Teacher` ;

CREATE TABLE IF NOT EXISTS `gitdb`.`Teacher` (
  `idTeacher` INT AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTeacher`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gitdb`.`TeacherProject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gitdb`.`TeacherProject` ;

CREATE TABLE IF NOT EXISTS `gitdb`.`TeacherProject` (
  `idTeacher` INT NOT NULL,
  `projectId` INT NOT NULL,
  PRIMARY KEY (`idTeacher`, `projectId`),
  INDEX `idProject_idx` (`projectId` ASC) VISIBLE,
  CONSTRAINT `idProjectForTeacher`
    FOREIGN KEY (`projectId`)
    REFERENCES `gitdb`.`Project` (`projectId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idTeacher`
    FOREIGN KEY (`idTeacher`)
    REFERENCES `gitdb`.`Teacher` (`idTeacher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
